### PR TITLE
Add an email form handler persistence setting

### PR DESCRIPTION
**Pull request by gnat42**
Sometimes I want to submit the form and check validity without persisting to the DB. This is backwards compatible but allows me to build live preview capabilities without requiring the system to persist the data in the database.

### CODE REVIEW

**Comment by snoob** [comment]
I don't really know why you need this but you can only make the flush optional as persist call doesn't changes the db.

I purpose to move the process on a protected method persistChanges (or flushChanges) in EmailFormHandler class instead of adding a property.

**Comment by gnat42** [comment]
So using this bundle we've built a system that allows for the template creation at the same time as doing variable substitution in the templates. We allow for a live preview without persisting the template.

**Comment by cedric-g** [comment]
To me this change is a part of the live preview you created, I don't think people will really need (or maybe understand) the aim of this change. I mean I understand you need it in your project (that's why the form handler is defined a service to allow to you to change the default behavior) but I don't think it's a general need.

**Comment by gnat42** [comment]
So I completely understand this is for my use case and likely a very not something that will be required by many. Its a minor backwards compatible change. Feel free to reject it however it breaks nothing to merge it.

**Pull request closed without merging**
